"""
Danh mục theo dõi, import từ DANH_MUC_THEO_DOI_16092026_114559.xlsx.
Cập nhật file này khi danh mục thay đổi (thêm/bớt mã) — không cần sửa
config.py hay các file tasks/.
"""

# Mã : Nhóm ngành (theo file gốc, chỉ để tham khảo)
WATCHLIST_WITH_SECTOR = {
    "DMX": "Bán lẻ",
    "FRT": "Bán lẻ",
    "PET": "Bán lẻ",
    "MWG": "Bán lẻ",
    "DGW": "Bán lẻ",
    "BVH": "Bảo hiểm",
    "MIG": "Bảo hiểm",
    "BCM": "Bất động sản",
    "SIP": "Bất động sản",
    "SZC": "Bất động sản",
    "VIC": "Bất động sản",
    "LHG": "Bất động sản",
    "VRE": "Bất động sản",
    "VHM": "Bất động sản",
    "IDC": "Bất động sản",
    "HTN": "Bất động sản",
    "NLG": "Bất động sản",
    "KDH": "Bất động sản",
    "KBC": "Bất động sản",
    "DIG": "Bất động sản",
    "HDC": "Bất động sản",
    "CEO": "Bất động sản",
    "PDR": "Bất động sản",
    "NVL": "Bất động sản",
    "TCH": "Bất động sản",
    "DXG": "Bất động sản",
    "CMG": "Công nghệ Thông tin",
    "FPT": "Công nghệ Thông tin",
    "OIL": "Dầu khí",
    "PLX": "Dầu khí",
    "PVB": "Dầu khí",
    "BSR": "Dầu khí",
    "PVC": "Dầu khí",
    "PVS": "Dầu khí",
    "PVD": "Dầu khí",
    "F88": "Dịch vụ tài chính",
    "VND": "Dịch vụ tài chính",
    "AGR": "Dịch vụ tài chính",
    "VIX": "Dịch vụ tài chính",
    "VPX": "Dịch vụ tài chính",
    "VCI": "Dịch vụ tài chính",
    "BSI": "Dịch vụ tài chính",
    "ORS": "Dịch vụ tài chính",
    "SHS": "Dịch vụ tài chính",
    "BVS": "Dịch vụ tài chính",
    "SSI": "Dịch vụ tài chính",
    "FTS": "Dịch vụ tài chính",
    "VDS": "Dịch vụ tài chính",
    "HCM": "Dịch vụ tài chính",
    "TCX": "Dịch vụ tài chính",
    "CTS": "Dịch vụ tài chính",
    "MBS": "Dịch vụ tài chính",
    "VCK": "Dịch vụ tài chính",
    "VJC": "Du lịch và Giải trí",
    "VPL": "Du lịch và Giải trí",
    "HVN": "Du lịch và Giải trí",
    "POW": "Điện, nước & xăng dầu khí đốt",
    "HDG": "Điện, nước & xăng dầu khí đốt",
    "NT2": "Điện, nước & xăng dầu khí đốt",
    "GAS": "Điện, nước & xăng dầu khí đốt",
    "REE": "Điện, nước & xăng dầu khí đốt",
    "GEG": "Điện, nước & xăng dầu khí đốt",
    "BWE": "Điện, nước & xăng dầu khí đốt",
    "GEE": "Hàng & Dịch vụ Công nghiệp",
    "PVT": "Hàng & Dịch vụ Công nghiệp",
    "VOS": "Hàng & Dịch vụ Công nghiệp",
    "HAH": "Hàng & Dịch vụ Công nghiệp",
    "ACV": "Hàng & Dịch vụ Công nghiệp",
    "VTP": "Hàng & Dịch vụ Công nghiệp",
    "GEX": "Hàng & Dịch vụ Công nghiệp",
    "GMD": "Hàng & Dịch vụ Công nghiệp",
    "SGP": "Hàng & Dịch vụ Công nghiệp",
    "TV2": "Hàng & Dịch vụ Công nghiệp",
    "VSC": "Hàng & Dịch vụ Công nghiệp",
    "VGT": "Hàng cá nhân & Gia dụng",
    "MSH": "Hàng cá nhân & Gia dụng",
    "PNJ": "Hàng cá nhân & Gia dụng",
    "TNG": "Hàng cá nhân & Gia dụng",
    "DRI": "Hóa chất",
    "GVR": "Hóa chất",
    "TRC": "Hóa chất",
    "BFC": "Hóa chất",
    "PHR": "Hóa chất",
    "PLC": "Hóa chất",
    "DPM": "Hóa chất",
    "DPR": "Hóa chất",
    "CSV": "Hóa chất",
    "DDV": "Hóa chất",
    "LAS": "Hóa chất",
    "DCM": "Hóa chất",
    "DGC": "Hóa chất",
    "EIB": "Ngân hàng",
    "STB": "Ngân hàng",
    "MBB": "Ngân hàng",
    "ABB": "Ngân hàng",
    "MSB": "Ngân hàng",
    "OCB": "Ngân hàng",
    "VIB": "Ngân hàng",
    "ACB": "Ngân hàng",
    "TCB": "Ngân hàng",
    "TPB": "Ngân hàng",
    "VPB": "Ngân hàng",
    "BID": "Ngân hàng",
    "VCB": "Ngân hàng",
    "SHB": "Ngân hàng",
    "HDB": "Ngân hàng",
    "CTG": "Ngân hàng",
    "LPB": "Ngân hàng",
    "BVB": "Ngân hàng",
    "MSR": "Tài nguyên Cơ bản",
    "VGS": "Tài nguyên Cơ bản",
    "GDA": "Tài nguyên Cơ bản",
    "KSV": "Tài nguyên Cơ bản",
    "HPG": "Tài nguyên Cơ bản",
    "HSG": "Tài nguyên Cơ bản",
    "PTB": "Tài nguyên Cơ bản",
    "NKG": "Tài nguyên Cơ bản",
    "VNM": "Thực phẩm và đồ uống",
    "MCH": "Thực phẩm và đồ uống",
    "DBC": "Thực phẩm và đồ uống",
    "HPA": "Thực phẩm và đồ uống",
    "SAB": "Thực phẩm và đồ uống",
    "BAF": "Thực phẩm và đồ uống",
    "VHC": "Thực phẩm và đồ uống",
    "PAN": "Thực phẩm và đồ uống",
    "MSN": "Thực phẩm và đồ uống",
    "YEG": "Truyền thông",
    "VGI": "Viễn thông",
    "FOX": "Viễn thông",
    "HBC": "Xây dựng và Vật liệu",
    "DC4": "Xây dựng và Vật liệu",
    "NTP": "Xây dựng và Vật liệu",
    "VGC": "Xây dựng và Vật liệu",
    "GEL": "Xây dựng và Vật liệu",
    "PC1": "Xây dựng và Vật liệu",
    "CTI": "Xây dựng và Vật liệu",
    "HHV": "Xây dựng và Vật liệu",
    "VCG": "Xây dựng và Vật liệu",
    "CTR": "Xây dựng và Vật liệu",
    "CTD": "Xây dựng và Vật liệu",
    "FCN": "Xây dựng và Vật liệu",
    "DPG": "Xây dựng và Vật liệu",
    "BMP": "Xây dựng và Vật liệu",
    "CII": "Xây dựng và Vật liệu",
    "DHG": "Y tế",
    "DVN": "Y tế",
    "DBD": "Y tế",
}

WATCHLIST = list(WATCHLIST_WITH_SECTOR.keys())
